apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-front
  name: app-front-svc
#  namespace: demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-front
  type: LoadBalancer
